[features]
seeds = false
skip-lint = false
[programs.localnet]
aperture_wormhole = "FVVVy4Uvdax5rjR4tiKq89TkgF8pByZfS7Xof6Z5bHQ2"
[programs.devnet]
aperture_wormhole = "FVVVy4Uvdax5rjR4tiKq89TkgF8pByZfS7Xof6Z5bHQ2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "keypairs/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
